language: java

notifications:
  email: false

jdk:
- oraclejdk8

install: true
script: ./travisSetup.sh

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
