language: java

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false

jdk:
- oraclejdk8

before_install:
  - chmod +x ./travisSetup.sh
  
install: true
script: ./travisSetup.sh

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  - bash ls -ltr /home/travis/build/Garlog7712/pentaho-kettle/.copilot/copilot_bom_bdio.jsonld
  - bash cat /home/travis/build/Garlog7712/pentaho-kettle/.copilot/copilot_bom_bdio.jsonld
