language: java

notifications:
  email: false

jdk:
- oraclejdk8

script: mvn clean install -s .travis.maven.settings.xml 

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
